### ISSUE TITLE
오류 발견

### ISSUE THREAD

**Issue by yh08037** [yh08037/Abstract_strategy_game#2]
![bug](https://user-images.githubusercontent.com/44798682/50686801-254aa880-1062-11e9-9a91-5f84acbc4d6a.PNG)

오른쪽 아래방향의 레이저가 왼쪽 수평방향으로 반사되었을 때 광원이 타지 않는 버그가 발견되었습니다

**Comment by Greathoney** [comment]
수정했습니다 ^^
