### ISSUE TITLE
수 물리기 (esc) 관련 오류

### ISSUE THREAD

**Issue by yh08037** [yh08037/Abstract_strategy_game#3]
![bug2-1](https://user-images.githubusercontent.com/44798682/50688319-4e6e3780-1068-11e9-9af6-900c761c18ec.PNG)
![bug2-2](https://user-images.githubusercontent.com/44798682/50688345-65148e80-1068-11e9-90f7-fa8416bdf867.PNG)
esc를 통해 수를 물렸을 때, 탔었던 광원이 되살아나는 버그가 발견되었습니다.

**Comment by Greathoney** [comment]
해결하였습니다 ^^ 어딜해결했는지는 안알랴줌

**Comment by yh08037** [comment]
여윽시 갓허니
스스로 깨우쳐보라는 말이로군요.... 반성하갰습니다
